/**
 * Demo account presets for PH, AU, CA, JP, UK, KSA, and a Global sampler.
 * Each preset is a full PersistShape override that can be loaded from
 * Settings → "Load demo account".
 *
 * Storage keys (bill.cat) stay in English — only display labels are localized.
 * Today reference: June 7, 2026.
 */

import type { Bill, BillCycleRecord } from "@/constants/data";
import { DEMO_BILLS, DEMO_ASK_HISTORY } from "@/constants/demoData";

// ─── helpers ────────────────────────────────────────────────────────────────

function hist(
  amount: number,
  periods: Array<{ period: string; onTime: boolean }>,
): BillCycleRecord[] {
  return periods.map(({ period, onTime }) => ({
    period,
    charged: amount,
    carriedIn: 0,
    totalDue: amount,
    paid: amount,
    rolledOver: 0,
    onTime,
  }));
}

const M5 = [
  { period: "2026-05", onTime: true },
  { period: "2026-04", onTime: true },
  { period: "2026-03", onTime: true },
  { period: "2026-02", onTime: true },
  { period: "2026-01", onTime: false },
];

// ─── Philippines ─────────────────────────────────────────────────────────────

const PH_CARD = "demo-ph-bdo";

const PH_BILLS: Bill[] = [
  {
    id: "demo-ph-meralco",
    provider: "Meralco",
    cat: "Electricity",
    icon: "zap",
    amount: 3800,
    dueDate: 5,
    dueDays: -2,
    dueLabel: "Jun 5",
    status: "due",
    kind: "Variable",
    house: "Home",
    paymentHistory: [
      { period: "2026-05", charged: 3200, carriedIn: 0, totalDue: 3200, paid: 3200, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 3450, carriedIn: 0, totalDue: 3450, paid: 3450, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 4100, carriedIn: 0, totalDue: 4100, paid: 4100, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 4800, carriedIn: 0, totalDue: 4800, paid: 4800, rolledOver: 0, onTime: false },
      { period: "2026-01", charged: 5100, carriedIn: 0, totalDue: 5100, paid: 5100, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-ph-water",
    provider: "Manila Water",
    cat: "Water",
    icon: "droplets",
    amount: 680,
    dueDate: 5,
    dueDays: -2,
    dueLabel: "Jun 5",
    status: "due",
    house: "Home",
    paymentHistory: hist(680, M5),
  },
  {
    id: "demo-ph-pldt",
    provider: "PLDT Fibr",
    cat: "Internet",
    icon: "wifi",
    amount: 1699,
    dueDate: 10,
    dueDays: 3,
    dueLabel: "Jun 10",
    status: "due",
    paymentHistory: hist(1699, M5),
  },
  {
    id: "demo-ph-globe",
    provider: "Globe",
    cat: "Mobile",
    icon: "smartphone",
    amount: 1299,
    dueDate: 12,
    dueDays: 5,
    dueLabel: "Jun 12",
    status: "due",
    paymentHistory: hist(1299, M5),
  },
  {
    id: PH_CARD,
    provider: "BDO Visa",
    cat: "Credit card",
    icon: "card",
    amount: 18400,
    dueDate: 15,
    dueDays: 8,
    dueLabel: "Jun 15",
    status: "due",
    statementDay: 1,
    paymentHistory: [
      { period: "2026-05", charged: 15200, carriedIn: 0, totalDue: 15200, paid: 15200, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 21000, carriedIn: 0, totalDue: 21000, paid: 21000, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 17500, carriedIn: 0, totalDue: 17500, paid: 17500, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 19800, carriedIn: 0, totalDue: 19800, paid: 19800, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 22300, carriedIn: 0, totalDue: 22300, paid: 22300, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-ph-netflix",
    provider: "Netflix",
    cat: "Streaming",
    icon: "spark",
    amount: 549,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: PH_CARD,
    paymentHistory: hist(549, M5),
  },
  {
    id: "demo-ph-spotify",
    provider: "Spotify",
    cat: "Streaming",
    icon: "spark",
    amount: 179,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: PH_CARD,
    paymentHistory: hist(179, M5),
  },
  {
    id: "demo-ph-youtube",
    provider: "YouTube Premium",
    cat: "Streaming",
    icon: "spark",
    amount: 169,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: PH_CARD,
    paymentHistory: hist(169, M5),
  },
  {
    id: "demo-ph-sss",
    provider: "SSS",
    cat: "Insurance",
    icon: "lock",
    amount: 1200,
    dueDate: 20,
    dueDays: 13,
    dueLabel: "Jun 20",
    status: "due",
    paymentHistory: hist(1200, M5),
  },
  {
    id: "demo-ph-pagibig",
    provider: "Pag-IBIG",
    cat: "Loan",
    icon: "home",
    amount: 2400,
    dueDate: 25,
    dueDays: 18,
    dueLabel: "Jun 25",
    status: "due",
    paymentHistory: hist(2400, M5),
  },
];

// ─── Australia ───────────────────────────────────────────────────────────────

const AU_CARD = "demo-au-anz";

const AU_BILLS: Bill[] = [
  {
    id: "demo-au-mortgage",
    provider: "CBA Home Loan",
    cat: "Rent / Mortgage",
    icon: "home",
    amount: 3250,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    subtype: "Mortgage",
    house: "Home",
    paymentHistory: hist(3250, M5),
  },
  {
    id: "demo-au-agl",
    provider: "AGL Energy",
    cat: "Electricity",
    icon: "zap",
    amount: 178,
    dueDate: 5,
    dueDays: -2,
    dueLabel: "Jun 5",
    status: "due",
    kind: "Variable",
    house: "Home",
    paymentHistory: [
      { period: "2026-05", charged: 145, carriedIn: 0, totalDue: 145, paid: 145, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 162, carriedIn: 0, totalDue: 162, paid: 162, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 210, carriedIn: 0, totalDue: 210, paid: 210, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 235, carriedIn: 0, totalDue: 235, paid: 235, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 252, carriedIn: 0, totalDue: 252, paid: 252, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-au-origin-gas",
    provider: "Origin Energy",
    cat: "Gas",
    icon: "flame",
    amount: 92,
    dueDate: 10,
    dueDays: 3,
    dueLabel: "Jun 10",
    status: "due",
    kind: "Variable",
    house: "Home",
    paymentHistory: [
      { period: "2026-05", charged: 78, carriedIn: 0, totalDue: 78, paid: 78, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 105, carriedIn: 0, totalDue: 105, paid: 105, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 128, carriedIn: 0, totalDue: 128, paid: 128, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 142, carriedIn: 0, totalDue: 142, paid: 142, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 155, carriedIn: 0, totalDue: 155, paid: 155, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-au-broadband",
    provider: "Aussie Broadband",
    cat: "Internet",
    icon: "wifi",
    amount: 89,
    dueDate: 12,
    dueDays: 5,
    dueLabel: "Jun 12",
    status: "due",
    paymentHistory: hist(89, M5),
  },
  {
    id: "demo-au-optus",
    provider: "Optus",
    cat: "Mobile",
    icon: "smartphone",
    amount: 69,
    dueDate: 15,
    dueDays: 8,
    dueLabel: "Jun 15",
    status: "due",
    paymentHistory: hist(69, M5),
  },
  {
    id: AU_CARD,
    provider: "ANZ Visa",
    cat: "Credit card",
    icon: "card",
    amount: 1380,
    dueDate: 18,
    dueDays: 11,
    dueLabel: "Jun 18",
    status: "due",
    statementDay: 1,
    paymentHistory: [
      { period: "2026-05", charged: 1150, carriedIn: 0, totalDue: 1150, paid: 1150, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 1620, carriedIn: 0, totalDue: 1620, paid: 1620, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 980,  carriedIn: 0, totalDue: 980,  paid: 980,  rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 1440, carriedIn: 0, totalDue: 1440, paid: 1440, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 1780, carriedIn: 0, totalDue: 1780, paid: 1780, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-au-netflix",
    provider: "Netflix",
    cat: "Streaming",
    icon: "spark",
    amount: 22.99,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: AU_CARD,
    paymentHistory: hist(22.99, M5),
  },
  {
    id: "demo-au-spotify",
    provider: "Spotify",
    cat: "Streaming",
    icon: "spark",
    amount: 12.99,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: AU_CARD,
    paymentHistory: hist(12.99, M5),
  },
  {
    id: "demo-au-disney",
    provider: "Disney+",
    cat: "Streaming",
    icon: "spark",
    amount: 13.99,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: AU_CARD,
    paymentHistory: hist(13.99, M5),
  },
  {
    id: "demo-au-medibank",
    provider: "Medibank",
    cat: "Insurance",
    icon: "lock",
    amount: 214,
    dueDate: 22,
    dueDays: 15,
    dueLabel: "Jun 22",
    status: "due",
    paymentHistory: hist(214, M5),
  },
  {
    id: "demo-au-toyota",
    provider: "Toyota Finance",
    cat: "Loan",
    icon: "car",
    amount: 620,
    dueDate: 28,
    dueDays: 21,
    dueLabel: "Jun 28",
    status: "due",
    paymentHistory: hist(620, M5),
  },
];

// ─── Canada ───────────────────────────────────────────────────────────────────

const CA_CARD = "demo-ca-td-visa";

const CA_BILLS: Bill[] = [
  {
    id: "demo-ca-mortgage",
    provider: "TD Mortgage",
    cat: "Rent / Mortgage",
    icon: "home",
    amount: 2680,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    subtype: "Mortgage",
    house: "Home",
    paymentHistory: hist(2680, M5),
  },
  {
    id: "demo-ca-hydro",
    provider: "Hydro One",
    cat: "Electricity",
    icon: "zap",
    amount: 125,
    dueDate: 5,
    dueDays: -2,
    dueLabel: "Jun 5",
    status: "due",
    kind: "Variable",
    house: "Home",
    paymentHistory: [
      { period: "2026-05", charged: 98,  carriedIn: 0, totalDue: 98,  paid: 98,  rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 115, carriedIn: 0, totalDue: 115, paid: 115, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 142, carriedIn: 0, totalDue: 142, paid: 142, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 168, carriedIn: 0, totalDue: 168, paid: 168, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 185, carriedIn: 0, totalDue: 185, paid: 185, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-ca-enbridge",
    provider: "Enbridge Gas",
    cat: "Gas",
    icon: "flame",
    amount: 88,
    dueDate: 10,
    dueDays: 3,
    dueLabel: "Jun 10",
    status: "due",
    kind: "Variable",
    house: "Home",
    paymentHistory: [
      { period: "2026-05", charged: 65,  carriedIn: 0, totalDue: 65,  paid: 65,  rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 95,  carriedIn: 0, totalDue: 95,  paid: 95,  rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 135, carriedIn: 0, totalDue: 135, paid: 135, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 158, carriedIn: 0, totalDue: 158, paid: 158, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 172, carriedIn: 0, totalDue: 172, paid: 172, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-ca-rogers",
    provider: "Rogers Internet",
    cat: "Internet",
    icon: "wifi",
    amount: 99,
    dueDate: 12,
    dueDays: 5,
    dueLabel: "Jun 12",
    status: "due",
    paymentHistory: hist(99, M5),
  },
  {
    id: "demo-ca-bell",
    provider: "Bell Mobile",
    cat: "Mobile",
    icon: "smartphone",
    amount: 78,
    dueDate: 15,
    dueDays: 8,
    dueLabel: "Jun 15",
    status: "due",
    paymentHistory: hist(78, M5),
  },
  {
    id: CA_CARD,
    provider: "TD Visa Infinite",
    cat: "Credit card",
    icon: "card",
    amount: 1920,
    dueDate: 20,
    dueDays: 13,
    dueLabel: "Jun 20",
    status: "due",
    statementDay: 1,
    paymentHistory: [
      { period: "2026-05", charged: 1650, carriedIn: 0, totalDue: 1650, paid: 1650, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 2100, carriedIn: 0, totalDue: 2100, paid: 2100, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 1420, carriedIn: 0, totalDue: 1420, paid: 1420, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 1880, carriedIn: 0, totalDue: 1880, paid: 1880, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 2240, carriedIn: 0, totalDue: 2240, paid: 2240, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-ca-netflix",
    provider: "Netflix",
    cat: "Streaming",
    icon: "spark",
    amount: 20.99,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: CA_CARD,
    paymentHistory: hist(20.99, M5),
  },
  {
    id: "demo-ca-crave",
    provider: "Crave",
    cat: "Streaming",
    icon: "spark",
    amount: 19.99,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: CA_CARD,
    paymentHistory: hist(19.99, M5),
  },
  {
    id: "demo-ca-spotify",
    provider: "Spotify",
    cat: "Streaming",
    icon: "spark",
    amount: 11.99,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: CA_CARD,
    paymentHistory: hist(11.99, M5),
  },
  {
    id: "demo-ca-sunlife",
    provider: "Sun Life",
    cat: "Insurance",
    icon: "lock",
    amount: 168,
    dueDate: 22,
    dueDays: 15,
    dueLabel: "Jun 22",
    status: "due",
    paymentHistory: hist(168, M5),
  },
  {
    id: "demo-ca-carloan",
    provider: "BMO Auto Loan",
    cat: "Loan",
    icon: "car",
    amount: 450,
    dueDate: 28,
    dueDays: 21,
    dueLabel: "Jun 28",
    status: "due",
    paymentHistory: hist(450, M5),
  },
];

// ─── Japan ────────────────────────────────────────────────────────────────────

const JP_CARD = "demo-jp-rakuten";

const JP_BILLS: Bill[] = [
  {
    id: "demo-jp-rent",
    provider: "家賃",
    cat: "Rent / Mortgage",
    icon: "home",
    amount: 98000,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    subtype: "Rent",
    house: "Home",
    paymentHistory: hist(98000, M5),
  },
  {
    id: "demo-jp-tepco",
    provider: "TEPCO",
    cat: "Electricity",
    icon: "zap",
    amount: 9200,
    dueDate: 5,
    dueDays: -2,
    dueLabel: "Jun 5",
    status: "due",
    kind: "Variable",
    house: "Home",
    paymentHistory: [
      { period: "2026-05", charged: 7800,  carriedIn: 0, totalDue: 7800,  paid: 7800,  rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 8500,  carriedIn: 0, totalDue: 8500,  paid: 8500,  rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 11200, carriedIn: 0, totalDue: 11200, paid: 11200, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 13400, carriedIn: 0, totalDue: 13400, paid: 13400, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 14800, carriedIn: 0, totalDue: 14800, paid: 14800, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-jp-tokyogas",
    provider: "東京ガス",
    cat: "Gas",
    icon: "flame",
    amount: 6100,
    dueDate: 10,
    dueDays: 3,
    dueLabel: "Jun 10",
    status: "due",
    kind: "Variable",
    house: "Home",
    paymentHistory: [
      { period: "2026-05", charged: 4800,  carriedIn: 0, totalDue: 4800,  paid: 4800,  rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 6500,  carriedIn: 0, totalDue: 6500,  paid: 6500,  rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 8200,  carriedIn: 0, totalDue: 8200,  paid: 8200,  rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 9400,  carriedIn: 0, totalDue: 9400,  paid: 9400,  rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 10100, carriedIn: 0, totalDue: 10100, paid: 10100, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-jp-softbank",
    provider: "SoftBank 光",
    cat: "Internet",
    icon: "wifi",
    amount: 5390,
    dueDate: 12,
    dueDays: 5,
    dueLabel: "Jun 12",
    status: "due",
    paymentHistory: hist(5390, M5),
  },
  {
    id: "demo-jp-docomo",
    provider: "NTT Docomo",
    cat: "Mobile",
    icon: "smartphone",
    amount: 8580,
    dueDate: 15,
    dueDays: 8,
    dueLabel: "Jun 15",
    status: "due",
    paymentHistory: hist(8580, M5),
  },
  {
    id: JP_CARD,
    provider: "楽天カード",
    cat: "Credit card",
    icon: "card",
    amount: 48600,
    dueDate: 18,
    dueDays: 11,
    dueLabel: "Jun 18",
    status: "due",
    statementDay: 1,
    paymentHistory: [
      { period: "2026-05", charged: 38200, carriedIn: 0, totalDue: 38200, paid: 38200, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 52000, carriedIn: 0, totalDue: 52000, paid: 52000, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 44500, carriedIn: 0, totalDue: 44500, paid: 44500, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 61200, carriedIn: 0, totalDue: 61200, paid: 61200, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 55800, carriedIn: 0, totalDue: 55800, paid: 55800, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-jp-netflix",
    provider: "Netflix",
    cat: "Streaming",
    icon: "spark",
    amount: 1490,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: JP_CARD,
    paymentHistory: hist(1490, M5),
  },
  {
    id: "demo-jp-spotify",
    provider: "Spotify",
    cat: "Streaming",
    icon: "spark",
    amount: 980,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: JP_CARD,
    paymentHistory: hist(980, M5),
  },
  {
    id: "demo-jp-apple",
    provider: "Apple One",
    cat: "Subscription",
    icon: "spark",
    amount: 1200,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: JP_CARD,
    paymentHistory: hist(1200, M5),
  },
  {
    id: "demo-jp-pension",
    provider: "国民年金",
    cat: "Insurance",
    icon: "lock",
    amount: 16520,
    dueDate: 25,
    dueDays: 18,
    dueLabel: "Jun 25",
    status: "due",
    paymentHistory: hist(16520, M5),
  },
  {
    id: "demo-jp-health",
    provider: "国民健康保険",
    cat: "Insurance",
    icon: "lock",
    amount: 12800,
    dueDate: 28,
    dueDays: 21,
    dueLabel: "Jun 28",
    status: "due",
    paymentHistory: hist(12800, M5),
  },
];

// ─── United Kingdom ───────────────────────────────────────────────────────────

const UK_CARD = "demo-uk-barclaycard";

const UK_BILLS: Bill[] = [
  {
    id: "demo-uk-rent",
    provider: "Landlord",
    cat: "Rent / Mortgage",
    icon: "home",
    amount: 1895,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    subtype: "Rent",
    house: "Home",
    paymentHistory: hist(1895, M5),
  },
  {
    id: "demo-uk-edf",
    provider: "EDF Energy",
    cat: "Electricity",
    icon: "zap",
    amount: 98,
    dueDate: 5,
    dueDays: -2,
    dueLabel: "Jun 5",
    status: "due",
    kind: "Variable",
    house: "Home",
    paymentHistory: [
      { period: "2026-05", charged: 82,  carriedIn: 0, totalDue: 82,  paid: 82,  rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 95,  carriedIn: 0, totalDue: 95,  paid: 95,  rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 118, carriedIn: 0, totalDue: 118, paid: 118, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 135, carriedIn: 0, totalDue: 135, paid: 135, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 148, carriedIn: 0, totalDue: 148, paid: 148, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-uk-british-gas",
    provider: "British Gas",
    cat: "Gas",
    icon: "flame",
    amount: 145,
    dueDate: 5,
    dueDays: -2,
    dueLabel: "Jun 5",
    status: "due",
    kind: "Variable",
    house: "Home",
    paymentHistory: [
      { period: "2026-05", charged: 110, carriedIn: 0, totalDue: 110, paid: 110, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 138, carriedIn: 0, totalDue: 138, paid: 138, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 182, carriedIn: 0, totalDue: 182, paid: 182, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 210, carriedIn: 0, totalDue: 210, paid: 210, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 225, carriedIn: 0, totalDue: 225, paid: 225, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-uk-virgin",
    provider: "Virgin Media",
    cat: "Internet",
    icon: "wifi",
    amount: 55,
    dueDate: 12,
    dueDays: 5,
    dueLabel: "Jun 12",
    status: "due",
    paymentHistory: hist(55, M5),
  },
  {
    id: "demo-uk-ee",
    provider: "EE Mobile",
    cat: "Mobile",
    icon: "smartphone",
    amount: 42,
    dueDate: 15,
    dueDays: 8,
    dueLabel: "Jun 15",
    status: "due",
    paymentHistory: hist(42, M5),
  },
  {
    id: UK_CARD,
    provider: "Barclaycard",
    cat: "Credit card",
    icon: "card",
    amount: 1150,
    dueDate: 18,
    dueDays: 11,
    dueLabel: "Jun 18",
    status: "due",
    statementDay: 1,
    paymentHistory: [
      { period: "2026-05", charged: 920,  carriedIn: 0, totalDue: 920,  paid: 920,  rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 1380, carriedIn: 0, totalDue: 1380, paid: 1380, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 850,  carriedIn: 0, totalDue: 850,  paid: 850,  rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 1120, carriedIn: 0, totalDue: 1120, paid: 1120, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 1450, carriedIn: 0, totalDue: 1450, paid: 1450, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-uk-netflix",
    provider: "Netflix",
    cat: "Streaming",
    icon: "spark",
    amount: 17.99,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: UK_CARD,
    paymentHistory: hist(17.99, M5),
  },
  {
    id: "demo-uk-spotify",
    provider: "Spotify",
    cat: "Streaming",
    icon: "spark",
    amount: 11.99,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: UK_CARD,
    paymentHistory: hist(11.99, M5),
  },
  {
    id: "demo-uk-amazon",
    provider: "Amazon Prime",
    cat: "Subscription",
    icon: "spark",
    amount: 8.99,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: UK_CARD,
    paymentHistory: hist(8.99, M5),
  },
  {
    id: "demo-uk-aviva",
    provider: "Aviva",
    cat: "Insurance",
    icon: "lock",
    amount: 92,
    dueDate: 22,
    dueDays: 15,
    dueLabel: "Jun 22",
    status: "due",
    paymentHistory: hist(92, M5),
  },
  {
    id: "demo-uk-loan",
    provider: "Santander Loan",
    cat: "Loan",
    icon: "lock",
    amount: 320,
    dueDate: 28,
    dueDays: 21,
    dueLabel: "Jun 28",
    status: "due",
    paymentHistory: hist(320, M5),
  },
];

// ─── Saudi Arabia ─────────────────────────────────────────────────────────────

const SA_CARD = "demo-sa-alrajhi";

const SA_BILLS: Bill[] = [
  {
    id: "demo-sa-rent",
    provider: "Landlord",
    cat: "Rent / Mortgage",
    icon: "home",
    amount: 5800,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    subtype: "Rent",
    house: "Home",
    paymentHistory: hist(5800, M5),
  },
  {
    id: "demo-sa-sec",
    provider: "Saudi Electricity",
    cat: "Electricity",
    icon: "zap",
    amount: 280,
    dueDate: 5,
    dueDays: -2,
    dueLabel: "Jun 5",
    status: "due",
    kind: "Variable",
    house: "Home",
    paymentHistory: [
      { period: "2026-05", charged: 245, carriedIn: 0, totalDue: 245, paid: 245, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 310, carriedIn: 0, totalDue: 310, paid: 310, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 380, carriedIn: 0, totalDue: 380, paid: 380, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 420, carriedIn: 0, totalDue: 420, paid: 420, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 395, carriedIn: 0, totalDue: 395, paid: 395, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-sa-water",
    provider: "NWC Water",
    cat: "Water",
    icon: "droplets",
    amount: 85,
    dueDate: 10,
    dueDays: 3,
    dueLabel: "Jun 10",
    status: "due",
    house: "Home",
    paymentHistory: hist(85, M5),
  },
  {
    id: "demo-sa-stc-net",
    provider: "STC Internet",
    cat: "Internet",
    icon: "wifi",
    amount: 348,
    dueDate: 12,
    dueDays: 5,
    dueLabel: "Jun 12",
    status: "due",
    paymentHistory: hist(348, M5),
  },
  {
    id: "demo-sa-stc-mobile",
    provider: "STC Mobile",
    cat: "Mobile",
    icon: "smartphone",
    amount: 198,
    dueDate: 15,
    dueDays: 8,
    dueLabel: "Jun 15",
    status: "due",
    paymentHistory: hist(198, M5),
  },
  {
    id: SA_CARD,
    provider: "Al Rajhi Visa",
    cat: "Credit card",
    icon: "card",
    amount: 3850,
    dueDate: 18,
    dueDays: 11,
    dueLabel: "Jun 18",
    status: "due",
    statementDay: 1,
    paymentHistory: [
      { period: "2026-05", charged: 2900, carriedIn: 0, totalDue: 2900, paid: 2900, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 4200, carriedIn: 0, totalDue: 4200, paid: 4200, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 3500, carriedIn: 0, totalDue: 3500, paid: 3500, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 4800, carriedIn: 0, totalDue: 4800, paid: 4800, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 5200, carriedIn: 0, totalDue: 5200, paid: 5200, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-sa-netflix",
    provider: "Netflix",
    cat: "Streaming",
    icon: "spark",
    amount: 45,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: SA_CARD,
    paymentHistory: hist(45, M5),
  },
  {
    id: "demo-sa-shahid",
    provider: "Shahid",
    cat: "Streaming",
    icon: "spark",
    amount: 55,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: SA_CARD,
    paymentHistory: hist(55, M5),
  },
  {
    id: "demo-sa-spotify",
    provider: "Spotify",
    cat: "Streaming",
    icon: "spark",
    amount: 35,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: SA_CARD,
    paymentHistory: hist(35, M5),
  },
  {
    id: "demo-sa-insurance",
    provider: "Tawuniya",
    cat: "Insurance",
    icon: "lock",
    amount: 680,
    dueDate: 22,
    dueDays: 15,
    dueLabel: "Jun 22",
    status: "due",
    paymentHistory: hist(680, M5),
  },
  {
    id: "demo-sa-carloan",
    provider: "Saudi Fransi Auto",
    cat: "Loan",
    icon: "car",
    amount: 1400,
    dueDate: 28,
    dueDays: 21,
    dueLabel: "Jun 28",
    status: "due",
    paymentHistory: hist(1400, M5),
  },
];

// ─── Global (all-category showcase, USD) ──────────────────────────────────────

const GLOBAL_CARD = "demo-global-chase";

const GLOBAL_BILLS: Bill[] = [
  {
    id: "demo-global-rent",
    provider: "Landlord",
    cat: "Rent / Mortgage",
    icon: "home",
    amount: 2800,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    subtype: "Rent",
    house: "Main home",
    paymentHistory: hist(2800, M5),
  },
  {
    id: "demo-global-aws",
    provider: "AWS",
    cat: "Web app",
    icon: "globe",
    amount: 285,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    isBusiness: true,
    businessName: "Freelance",
    paymentHistory: hist(285, [
      { period: "2026-05", onTime: true },
      { period: "2026-04", onTime: true },
      { period: "2026-03", onTime: true },
    ]),
  },
  {
    id: "demo-global-electric",
    provider: "Con Edison",
    cat: "Electricity",
    icon: "zap",
    amount: 148,
    dueDate: 5,
    dueDays: -2,
    dueLabel: "Jun 5",
    status: "due",
    kind: "Variable",
    house: "Main home",
    paymentHistory: [
      { period: "2026-05", charged: 112, carriedIn: 0, totalDue: 112, paid: 112, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 98,  carriedIn: 0, totalDue: 98,  paid: 98,  rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 155, carriedIn: 0, totalDue: 155, paid: 155, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 172, carriedIn: 0, totalDue: 172, paid: 172, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 185, carriedIn: 0, totalDue: 185, paid: 185, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-global-gas",
    provider: "National Grid",
    cat: "Gas",
    icon: "flame",
    amount: 72,
    dueDate: 7,
    dueDays: 0,
    dueLabel: "Jun 7",
    status: "due",
    kind: "Variable",
    house: "Main home",
    paymentHistory: [
      { period: "2026-05", charged: 58,  carriedIn: 0, totalDue: 58,  paid: 58,  rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 85,  carriedIn: 0, totalDue: 85,  paid: 85,  rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 102, carriedIn: 0, totalDue: 102, paid: 102, rolledOver: 0, onTime: true },
    ],
  },
  {
    id: "demo-global-internet",
    provider: "Spectrum",
    cat: "Internet",
    icon: "wifi",
    amount: 89,
    dueDate: 10,
    dueDays: 3,
    dueLabel: "Jun 10",
    status: "due",
    paymentHistory: hist(89, M5),
  },
  {
    id: "demo-global-mobile",
    provider: "T-Mobile",
    cat: "Mobile",
    icon: "smartphone",
    amount: 85,
    dueDate: 12,
    dueDays: 5,
    dueLabel: "Jun 12",
    status: "due",
    paymentHistory: hist(85, M5),
  },
  {
    id: GLOBAL_CARD,
    provider: "Chase Sapphire",
    cat: "Credit card",
    icon: "card",
    amount: 1950,
    dueDate: 15,
    dueDays: 8,
    dueLabel: "Jun 15",
    status: "due",
    statementDay: 1,
    paymentHistory: [
      { period: "2026-05", charged: 1620, carriedIn: 0, totalDue: 1620, paid: 1620, rolledOver: 0, onTime: true },
      { period: "2026-04", charged: 2100, carriedIn: 0, totalDue: 2100, paid: 2100, rolledOver: 0, onTime: true },
      { period: "2026-03", charged: 1480, carriedIn: 0, totalDue: 1480, paid: 1480, rolledOver: 0, onTime: true },
      { period: "2026-02", charged: 1890, carriedIn: 0, totalDue: 1890, paid: 1890, rolledOver: 0, onTime: true },
      { period: "2026-01", charged: 2240, carriedIn: 0, totalDue: 2240, paid: 2240, rolledOver: 0, onTime: false },
    ],
  },
  {
    id: "demo-global-netflix",
    provider: "Netflix",
    cat: "Streaming",
    icon: "spark",
    amount: 22.99,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: GLOBAL_CARD,
    paymentHistory: hist(22.99, M5),
  },
  {
    id: "demo-global-spotify",
    provider: "Spotify",
    cat: "Streaming",
    icon: "spark",
    amount: 11.99,
    dueDate: 1,
    dueDays: -6,
    dueLabel: "Jun 1",
    status: "due",
    chargedToCard: true,
    parentCardId: GLOBAL_CARD,
    paymentHistory: hist(11.99, M5),
  },
  {
    id: "demo-global-hulu",
    provider: "Hulu",
    cat: "Streaming",
    icon: "spark",
    amount: 17.99,
    dueDate: 10,
    dueDays: 3,
    dueLabel: "Jun 10",
    status: "due",
    chargedToCard: true,
    parentCardId: GLOBAL_CARD,
    paymentHistory: hist(17.99, M5),
  },
  {
    id: "demo-global-adobe",
    provider: "Adobe CC",
    cat: "Web app",
    icon: "spark",
    amount: 59.99,
    dueDate: 15,
    dueDays: 8,
    dueLabel: "Jun 15",
    status: "due",
    chargedToCard: true,
    parentCardId: GLOBAL_CARD,
    isBusiness: true,
    businessName: "Freelance",
    paymentHistory: hist(59.99, M5),
  },
  {
    id: "demo-global-gym",
    provider: "Planet Fitness",
    cat: "Health & Fitness",
    icon: "spark",
    amount: 24.99,
    dueDate: 20,
    dueDays: 13,
    dueLabel: "Jun 20",
    status: "due",
    chargedToCard: true,
    parentCardId: GLOBAL_CARD,
    paymentHistory: hist(24.99, M5),
  },
  {
    id: "demo-global-geico",
    provider: "GEICO",
    cat: "Insurance",
    icon: "lock",
    amount: 195,
    dueDate: 18,
    dueDays: 11,
    dueLabel: "Jun 18",
    status: "due",
    paymentHistory: hist(195, M5),
  },
  {
    id: "demo-global-vanguard",
    provider: "Vanguard",
    cat: "Savings / Investment",
    icon: "chart",
    amount: 500,
    dueDate: 22,
    dueDays: 15,
    dueLabel: "Jun 22",
    status: "due",
    paymentHistory: hist(500, M5),
  },
  {
    id: "demo-global-shopify",
    provider: "Shopify",
    cat: "Web app",
    icon: "globe",
    amount: 79,
    dueDate: 25,
    dueDays: 18,
    dueLabel: "Jun 25",
    status: "due",
    isBusiness: true,
    businessName: "Freelance",
    paymentHistory: hist(79, M5),
  },
  {
    id: "demo-global-loan",
    provider: "Sallie Mae",
    cat: "Loan",
    icon: "lock",
    amount: 380,
    dueDate: 28,
    dueDays: 21,
    dueLabel: "Jun 28",
    status: "due",
    paymentHistory: hist(380, M5),
  },
];

// ─── Ask histories ────────────────────────────────────────────────────────────

const PH_ASK = [
  { role: "user" as const,   text: "Magkano pa ang babayaran ko ngayong buwan?" },
  { role: "judith" as const, text: "May ₱26,779 ka pang babayaran ngayong Hunyo, Maria. Ang Meralco (₱3,800) at Manila Water (₱680) ay nagreresulta na — 2 araw na late na sila. Pinakamalapit na due mo ay ang PLDT (₱1,699) sa Jun 10, tapos Globe (₱1,299) sa Jun 12. Gusto mo bang i-breakdown per kategorya?" },
  { role: "user" as const,   text: "Magkano ang BDO ko this month?" },
  { role: "judith" as const, text: "Ang BDO Visa mo ngayong Hunyo ay ₱18,400, due sa Jun 15 — 8 araw pa. May ₱897 na auto-charges dito: Netflix (₱549), Spotify (₱179), at YouTube Premium (₱169). On-time ka sa lahat ng nakaraang 4 na buwan — solid ang record mo." },
];

const AU_ASK = [
  { role: "user" as const,   text: "How much do I have left to pay this month?" },
  { role: "judith" as const, text: "You've got A$5,349 still due in June, Liam. Your mortgage (A$3,250) and AGL electricity (A$178) are both overdue — 6 days past due on the mortgage, 2 on the electricity. Next up is Origin gas (A$92) on Jun 10. Want me to break it down by category?" },
  { role: "user" as const,   text: "What are my biggest bills?" },
  { role: "judith" as const, text: "Your top 3 this month: CBA mortgage at A$3,250, ANZ Visa at A$1,380, and Toyota Finance at A$620. Those three alone are A$5,250 — about 98% of your total. Everything else is utilities and subscriptions." },
];

const CA_ASK = [
  { role: "user" as const,   text: "How much do I owe this month?" },
  { role: "judith" as const, text: "You're looking at CA$5,907 in June, Sophie. The TD mortgage (CA$2,680) and Hydro One (CA$125) are already overdue — both from June 1st. Enbridge gas (CA$88) is next on Jun 10, then Rogers (CA$99) on Jun 12. Grab those overdue ones first!" },
  { role: "user" as const,   text: "What's on my TD Visa this month?" },
  { role: "judith" as const, text: "Your TD Visa statement is CA$1,920, due Jun 20 — 13 days out. CA$52.97 of that is subscriptions on auto-pay: Netflix (CA$20.99), Crave (CA$19.99), and Spotify (CA$11.99). You've been on time 4 of the last 5 months — pretty solid." },
];

const JP_ASK = [
  { role: "user" as const,   text: "今月いくら残ってますか？" },
  { role: "judith" as const, text: "6月はまだ¥207,070の支払いが残っています、Yukiさん。家賃(¥98,000)とTEPCO(¥9,200)がすでに延滞中です — どちらも6月1日・5日が期限でした。次は東京ガス(¥6,100)が6月10日です。延滞分を先に片付けましょう！" },
  { role: "user" as const,   text: "楽天カードはいくらですか？" },
  { role: "judith" as const, text: "楽天カードの今月の請求は¥48,600で、支払期限は6月18日 — あと11日あります。うち¥3,670がサブスク自動引き落とし：Netflix(¥1,490)、Spotify(¥980)、Apple One(¥1,200)です。過去4ヶ月は全て期限通りに支払えていますよ。" },
];

const UK_ASK = [
  { role: "user" as const,   text: "How much do I owe in June?" },
  { role: "judith" as const, text: "You've got £3,795 left to pay in June, Oliver. The rent (£1,895) and two energy bills — EDF (£98) and British Gas (£145) — are already overdue. That's £2,138 needing attention right away. Virgin Media (£55) is next on Jun 12. Want a full breakdown?" },
  { role: "user" as const,   text: "What's my biggest expense category?" },
  { role: "judith" as const, text: "Rent / Mortgage is your biggest category by far at £1,895 — that's 50% of your total June bills. Next is Credit card at £1,150, then Gas at £145, and Insurance at £92. The subscriptions (Netflix, Spotify, Amazon Prime) add another £38.97 through your Barclaycard." },
];

const SA_ASK = [
  { role: "user" as const,   text: "How much do I still owe this month?" },
  { role: "judith" as const, text: "You have ﷼12,521 still due in June, Khalid. Rent (﷼5,800) and Saudi Electricity (﷼280) are already overdue from June 1st and 5th. NWC Water (﷼85) is next on Jun 10, then STC Internet (﷼348) on Jun 12. Settle the overdue ones first." },
  { role: "user" as const,   text: "What's on my Al Rajhi card?" },
  { role: "judith" as const, text: "Your Al Rajhi Visa statement is ﷼3,850, due Jun 18 — 11 days away. That includes ﷼135 in auto-subscriptions: Netflix (﷼45), Shahid (﷼55), and Spotify (﷼35). You've paid on time 4 of the last 5 months — keep that up!" },
];

const GLOBAL_ASK = [
  { role: "user" as const,   text: "How much do I still owe this month?" },
  { role: "judith" as const, text: "You've got $5,347 still due in June across 15 bills. Three are already overdue: rent ($2,800, 6 days late), AWS ($285, 6 days late), and Con Edison ($148, 2 days late) — $3,233 needs your attention now. National Grid gas ($72) is due today. Next up: Spectrum ($89) on Jun 10. Want a breakdown by category?" },
  { role: "user" as const,   text: "What's on my Chase Sapphire?" },
  { role: "judith" as const, text: "Your Chase Sapphire is $1,950, due Jun 15 — 8 days out. You've got $137.95 in auto-charges: Netflix ($23), Spotify ($12), Hulu ($18), Adobe CC ($60, Freelance), and Planet Fitness ($25). You've paid on time 4 of the last 5 months. Good track record." },
];

// ─── Exported demo account list ───────────────────────────────────────────────

export interface DemoAccount {
  code: string;
  flag: string;
  label: string;
  subtitle: string;
  preset: {
    bills: Bill[];
    asksLeft: number;
    tier: "free" | "chat" | "voice";
    name: string;
    persona: "pro" | "caring" | "funny";
    voiceId: string;
    language: string;
    theme: "system" | "dark" | "light";
    accent: string;
    countryCode: string;
    currency: string;
    toggles: {
      dueReminders: boolean;
      widget: boolean;
      watch: boolean;
      nudges: boolean;
      voiceReplies: boolean;
    };
    reduceMotion: boolean;
    faceIdLock: boolean;
    onboarded: true;
    onbIdx: 0;
    guest: false;
    monthlyIncome: number;
    incomeByMonth: Record<string, number>;
    askHistory: Array<{ role: "user" | "judith"; text: string }>;
  };
}

export const DEMO_ACCOUNTS: DemoAccount[] = [
  {
    code: "US",
    flag: "🇺🇸",
    label: "United States",
    subtitle: "Alex · $ · English",
    preset: {
      bills: DEMO_BILLS, asksLeft: 3, tier: "chat", name: "Alex",
      persona: "funny", voiceId: "rachel", language: "en",
      theme: "system", accent: "mint", countryCode: "US", currency: "$",
      toggles: { dueReminders: true, widget: true, watch: false, nudges: true, voiceReplies: true },
      reduceMotion: false, faceIdLock: false, onboarded: true, onbIdx: 0, guest: false,
      monthlyIncome: 5500, incomeByMonth: {}, askHistory: DEMO_ASK_HISTORY,
    },
  },
  {
    code: "PH",
    flag: "🇵🇭",
    label: "Philippines",
    subtitle: "Maria · ₱ · Tagalog",
    preset: {
      bills: PH_BILLS, asksLeft: 3, tier: "chat", name: "Maria",
      persona: "caring", voiceId: "rachel", language: "fil",
      theme: "system", accent: "mint", countryCode: "PH", currency: "₱",
      toggles: { dueReminders: true, widget: true, watch: false, nudges: true, voiceReplies: true },
      reduceMotion: false, faceIdLock: false, onboarded: true, onbIdx: 0, guest: false,
      monthlyIncome: 45000, incomeByMonth: {}, askHistory: PH_ASK,
    },
  },
  {
    code: "AU",
    flag: "🇦🇺",
    label: "Australia",
    subtitle: "Liam · A$ · English",
    preset: {
      bills: AU_BILLS, asksLeft: 3, tier: "chat", name: "Liam",
      persona: "pro", voiceId: "rachel", language: "en",
      theme: "system", accent: "mint", countryCode: "AU", currency: "A$",
      toggles: { dueReminders: true, widget: true, watch: false, nudges: true, voiceReplies: true },
      reduceMotion: false, faceIdLock: false, onboarded: true, onbIdx: 0, guest: false,
      monthlyIncome: 8500, incomeByMonth: {}, askHistory: AU_ASK,
    },
  },
  {
    code: "CA",
    flag: "🇨🇦",
    label: "Canada",
    subtitle: "Sophie · CA$ · English",
    preset: {
      bills: CA_BILLS, asksLeft: 3, tier: "chat", name: "Sophie",
      persona: "funny", voiceId: "rachel", language: "en",
      theme: "system", accent: "mint", countryCode: "CA", currency: "CA$",
      toggles: { dueReminders: true, widget: true, watch: false, nudges: true, voiceReplies: true },
      reduceMotion: false, faceIdLock: false, onboarded: true, onbIdx: 0, guest: false,
      monthlyIncome: 7000, incomeByMonth: {}, askHistory: CA_ASK,
    },
  },
  {
    code: "JP",
    flag: "🇯🇵",
    label: "Japan",
    subtitle: "Yuki · ¥ · Japanese",
    preset: {
      bills: JP_BILLS, asksLeft: 3, tier: "chat", name: "Yuki",
      persona: "pro", voiceId: "rachel", language: "ja",
      theme: "system", accent: "mint", countryCode: "JP", currency: "¥",
      toggles: { dueReminders: true, widget: true, watch: false, nudges: true, voiceReplies: true },
      reduceMotion: false, faceIdLock: false, onboarded: true, onbIdx: 0, guest: false,
      monthlyIncome: 400000, incomeByMonth: {}, askHistory: JP_ASK,
    },
  },
  {
    code: "GB",
    flag: "🇬🇧",
    label: "United Kingdom",
    subtitle: "Oliver · £ · English",
    preset: {
      bills: UK_BILLS, asksLeft: 3, tier: "chat", name: "Oliver",
      persona: "caring", voiceId: "rachel", language: "en",
      theme: "system", accent: "mint", countryCode: "GB", currency: "£",
      toggles: { dueReminders: true, widget: true, watch: false, nudges: true, voiceReplies: true },
      reduceMotion: false, faceIdLock: false, onboarded: true, onbIdx: 0, guest: false,
      monthlyIncome: 4800, incomeByMonth: {}, askHistory: UK_ASK,
    },
  },
  {
    code: "SA",
    flag: "🇸🇦",
    label: "Saudi Arabia",
    subtitle: "Khalid · ﷼ · Arabic",
    preset: {
      bills: SA_BILLS, asksLeft: 3, tier: "chat", name: "Khalid",
      persona: "pro", voiceId: "rachel", language: "ar",
      theme: "system", accent: "mint", countryCode: "SA", currency: "﷼",
      toggles: { dueReminders: true, widget: true, watch: false, nudges: true, voiceReplies: true },
      reduceMotion: false, faceIdLock: false, onboarded: true, onbIdx: 0, guest: false,
      monthlyIncome: 18000, incomeByMonth: {}, askHistory: SA_ASK,
    },
  },
  {
    code: "GLOBAL",
    flag: "🌍",
    label: "Global Showcase",
    subtitle: "Alex · $ · All categories",
    preset: {
      bills: GLOBAL_BILLS, asksLeft: 3, tier: "chat", name: "Alex",
      persona: "funny", voiceId: "rachel", language: "en",
      theme: "system", accent: "mint", countryCode: "US", currency: "$",
      toggles: { dueReminders: true, widget: true, watch: false, nudges: true, voiceReplies: true },
      reduceMotion: false, faceIdLock: false, onboarded: true, onbIdx: 0, guest: false,
      monthlyIncome: 12000, incomeByMonth: {}, askHistory: GLOBAL_ASK,
    },
  },
];
