import {
  LegalShell,
  Section,
  Subsection,
  hrefFor,
  pStyle,
  ulStyle,
  liStyle,
  linkStyle,
  contactBoxStyle,
} from "../components/legal";

export default function TermsOfUse() {
  return (
    <LegalShell
      page="terms"
      title="Terms of Use"
      meta="Effective date: June 5, 2026 · App: Judith – Bill Tracker · Developer: Thursday MX"
      intro="These Terms of Use govern your use of Judith. By creating an account or using the app, you agree to these terms. Please read them alongside our Privacy Policy."
    >
      <Section title="1. Acceptance of These Terms">
        <p style={pStyle}>By downloading, accessing, or using Judith (the "App"), you agree to be bound by these Terms of Use (the "Terms"). If you do not agree, please do not use the App. These Terms form a legal agreement between you and <strong>Thursday MX</strong> ("we", "us", "our").</p>
        <p style={pStyle}>Your use of the App is also governed by our <a href={hrefFor("privacy")} style={linkStyle}>Privacy Policy</a>, which explains how we handle your data.</p>
      </Section>

      <Section title="2. Eligibility">
        <p style={pStyle}>You must be at least 13 years old to use Judith. By using the App, you confirm that you meet this requirement and that the information you provide is accurate.</p>
      </Section>

      <Section title="3. The Service">
        <p style={pStyle}>Judith helps you track bills, due dates, and recurring charges, and offers an AI assistant ("Ask Judith") that can answer questions about the bills you record and optionally read responses aloud. The App is provided for your personal use to manage your own finances.</p>
      </Section>

      <Section title="4. Your Account">
        <p style={pStyle}>You are responsible for maintaining the security of your account and for all activity that occurs under it. Sign in is handled by Apple or Google — keep those accounts secure. Notify us promptly if you believe your account has been compromised.</p>
      </Section>

      <Section title="5. Subscriptions & Payments">
        <Subsection title="Plans">
          <p style={pStyle}>Core bill tracking and a limited number of free Ask Judith questions are included at no cost. Paid plans unlock more:</p>
          <ul style={ulStyle}>
            <li style={liStyle}><strong>Chat Ask</strong> — unlimited text questions to Judith.</li>
            <li style={liStyle}><strong>Voice Ask</strong> — everything in Chat, plus spoken voice responses.</li>
          </ul>
        </Subsection>
        <Subsection title="Billing">
          <p style={pStyle}>Paid plans are billed through the <strong>Apple App Store</strong> or <strong>Google Play</strong> and managed by RevenueCat. Subscriptions renew automatically until cancelled. You can manage or cancel your subscription at any time in your App Store or Google Play account settings. Refunds are handled according to the policies of the applicable app store.</p>
        </Subsection>
        <Subsection title="Price changes">
          <p style={pStyle}>We may change plan pricing or features. Where required, we will give notice and obtain consent before a change affects an existing subscription.</p>
        </Subsection>
      </Section>

      <Section title="6. Acceptable Use & Fair Use">
        <p style={pStyle}>Judith is offered for normal, personal use. To keep the service fast, reliable, and affordable for everyone, you agree to the following.</p>

        <Subsection title="Personal use only">
          <p style={pStyle}>Use Judith for your own bills and finances. The App is not licensed for commercial resale, for managing accounts on behalf of others as a service, or for sharing a single account among multiple people.</p>
        </Subsection>

        <Subsection title="Reasonable limits">
          <p style={pStyle}>The AI assistant, voice playback, and bill-scanning features are subject to <strong>reasonable usage limits</strong> to prevent abuse and runaway costs. Normal personal use will not come close to these limits. If you reach a limit, the App will ask you to wait a short while before trying again. We may adjust these limits over time to protect the service.</p>
        </Subsection>

        <Subsection title="No automated or abusive access">
          <p style={pStyle}>You agree not to:</p>
          <ul style={ulStyle}>
            <li style={liStyle}>Access the App or its backend through bots, scripts, scrapers, or other automated means;</li>
            <li style={liStyle}>Attempt to bypass, disable, or interfere with rate limits, authentication, or other security measures;</li>
            <li style={liStyle}>Send excessive, bulk, or artificially generated requests to the AI or voice features;</li>
            <li style={liStyle}>Resell, redistribute, or commercially exploit the App or any responses generated by it;</li>
            <li style={liStyle}>Reverse engineer, probe, or attempt to extract the App's underlying models, prompts, or source code;</li>
            <li style={liStyle}>Use the App for any unlawful, harmful, or fraudulent purpose.</li>
          </ul>
        </Subsection>

        <Subsection title="Enforcement">
          <p style={pStyle}>If we detect use that violates this section or threatens the stability of the service, we may temporarily throttle, suspend, or terminate access — with notice where reasonable.</p>
        </Subsection>
      </Section>

      <Section title="7. AI Assistant Disclaimer">
        <p style={pStyle}>Ask Judith provides general, informational responses generated by AI based on the bills you record. It is <strong>not</strong> professional financial, legal, tax, or accounting advice. AI responses may be incomplete or inaccurate — always verify important due dates and amounts against your official bills and statements before acting on them.</p>
      </Section>

      <Section title="8. Intellectual Property">
        <p style={pStyle}>The App, including its design, software, and content (excluding your own bill data), is owned by Thursday MX and protected by intellectual property laws. We grant you a limited, non-exclusive, non-transferable license to use the App for personal purposes in accordance with these Terms. You retain ownership of the bill data you enter.</p>
      </Section>

      <Section title="9. Third-Party Services">
        <p style={pStyle}>Judith relies on third-party providers — including Anthropic, ElevenLabs, RevenueCat, Supabase, Apple, and Google. Your use of features powered by these providers is also subject to their respective terms and privacy policies. We are not responsible for the practices of third-party services.</p>
      </Section>

      <Section title="10. Termination">
        <p style={pStyle}>You may stop using Judith and delete your account at any time from within the App. We may suspend or terminate your access if you violate these Terms or if required to protect the service or comply with the law. On termination, your data is handled as described in our <a href={hrefFor("privacy")} style={linkStyle}>Privacy Policy</a>.</p>
      </Section>

      <Section title="11. Disclaimers & Limitation of Liability">
        <p style={pStyle}>Judith is provided "as is" and "as available", without warranties of any kind, whether express or implied. We do not guarantee that the App will be uninterrupted, error-free, or that reminders will always be delivered. You are responsible for paying your bills on time.</p>
        <p style={pStyle}>To the maximum extent permitted by law, Thursday MX will not be liable for any indirect, incidental, or consequential damages — including missed payments, late fees, or service cutoffs — arising from your use of, or inability to use, the App. Where liability cannot be excluded, it is limited to the amount you paid us in the twelve months before the claim.</p>
      </Section>

      <Section title="12. Changes to These Terms">
        <p style={pStyle}>We may update these Terms from time to time. When we do, we will update the effective date at the top of this page, and significant changes will be communicated in-app. Continued use of Judith after changes constitutes acceptance of the updated Terms.</p>
      </Section>

      <Section title="13. Governing Law">
        <p style={pStyle}>These Terms are governed by the laws of the Republic of the Philippines, without regard to its conflict-of-laws rules. Any disputes will be subject to the exclusive jurisdiction of the courts located in the Philippines, except where mandatory consumer-protection laws in your country of residence provide otherwise.</p>
      </Section>

      <Section title="14. Contact Us">
        <p style={pStyle}>If you have questions about these Terms, please contact:</p>
        <div style={contactBoxStyle}>
          <p style={{ margin: "0 0 4px", fontWeight: 600, color: "#1a1a1a" }}>Thursday MX</p>
          <p style={{ margin: "0 0 4px", color: "#555" }}>Judith – Bill Tracker</p>
          <p style={{ margin: 0 }}>
            <a href="mailto:support@judithforduedates.com" style={linkStyle}>support@judithforduedates.com</a>
          </p>
          <p style={{ margin: "4px 0 0", color: "#555" }}>
            <a href="https://judithforduedates.com" style={linkStyle} target="_blank" rel="noopener noreferrer">judithforduedates.com</a>
          </p>
        </div>
      </Section>
    </LegalShell>
  );
}
